import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from 'next/image'
import { api, RouterOutputs } from "~/utils/api";
import dayjs from 'dayjs'
import relativetime from 'dayjs/plugin/relativeTime'
dayjs.extend(relativetime)


const CreatePostWizard = () => {
  const { user } = useUser()

  console.log(user);

  if (!user) return null

  return (
    <div className="flex gap-3 w-full">
      <Image
        src={user.profileImageUrl}
        alt="user profile"
        className="h-14 w-14"
        width={24}
        height={24} />
      <input placeholder="Type some emojis" className="bg-transparent grow" />
    </div>
  )
}
type PostWithUser = RouterOutputs["posts"]["getAll"][number]
const PostView = (props: PostWithUser) => {
  const { post, author } = props
  return (
    <div className="border-b border-slate-400 p-4 gap-3 flex">
      <Image
        src={author.image}
        alt="author"
        className="h-14 w-14"
        width={24}
        height={24}
      />

      <div className="flex flex-col">
        <div className="flex gap-1 text-slate-400">
          <span>{`@${author.username}`}</span>
          <span className="font-thin">{`· ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span className="">{post.content}</span>
      </div>
    </div >
  )
}

const Home: NextPage = () => {
  const user = useUser()
  const { data, isLoading } = api.posts.getAll.useQuery()

  if (isLoading) return <div>Loading...</div>

  if (!data) return <div>Something went wrong</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full h-full md:max-w-3xl border-x border-slate-400 ">
          <div className="text-white flex border-b border-slate-400 p-4 ">
            {!user.isSignedIn && (
              <div className="flex justify-center"><SignInButton /></div>)}

            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data?.map((fullPost) => (
              <PostView key={fullPost.post.id} {...fullPost} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
